# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANT_VERSION = "2.2.10"

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "hashicorp/bionic64"

    # TODO:
    #
    # expose k8s ports so waypoint can connect from host machine
    #
    # a provisioner that installs
    #
    # golang
    # docker desktop
    # kind cli
    #
    # creates cluster
    #
  end
end
